# **Türkçe Dil Modellerine Fine-tuning Yapılması**

*   **Fine-tuning** (ince ayar), daha önce eğitilmiş bir modelin belirli göreve özgü bir veri kümesi üzerinde daha da eğitilmesini içerir. Bu, modelin geniş bilgisiyle göreve özgü kavramları geliştirmesine olanak tanır.

*   Bu görev için "**ytu-ce-cosmos/turkish-gpt2**" modelini "**merve/turkish instructions**" veri seti üzerinde eğitilecektir.

*   Kullanılacak olan model **124 milyon parametreye** sahip olup **Türkçe'de pretraining** işlemine tabi tutulmuştur.



In [ ]:
!pip install transformers
!pip install accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.6/302.6 kB 7.3 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [ ]:
from transformers import AutoTokenizer, GPT2LMHeadModel
from transformers import pipeline

In [ ]:
model = GPT2LMHeadModel.from_pretrained("ytu-ce-cosmos/turkish-gpt2")
tokenizer = AutoTokenizer.from_pretrained("ytu-ce-cosmos/turkish-gpt2")

# Huggingface'ten bir model ve tokenizer kullanılır.

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/893 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/537 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/927k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/585k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.37M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/438 [00:00<?, ?B/s]

In [ ]:
#model.save_pretrained("MycosmosGPT")
#tokenizer.save_pretrained("MycosmosGPT")

# Bir modeli yerel olarak kaydeder.

In [ ]:
#model = GPT2LMHeadModel.from_pretrained("./MycosmosGPT")
#tokenizer = AutoTokenizer.from_pretrained("./MycosmosGPT")

# Yerelde dosyaları bulunan bir modeli kullanır.

In [ ]:
if tokenizer.pad_token is None:
  tokenizer.pad_token = tokenizer.eos_token
  tokenizer.pad_token_id = tokenizer.eos_token_id

Aşağıda çıktı üretimi için gerekl aşamalar gösterilmiştir.

*   Girdi metni, yukarıda yüklenen tokenizer ile tokenlara ayrılır.
*   Bu tokenlar modele verilerek çıktı elde edilir.
*   Üretilen metin tokenlar halindedir. Çıktının metin olarak görülebilmesi için bu tokenların metin karşılıkları elde edilmelidir.

In [ ]:
prompt = "Zor günlere rağmen hayatı sevmek için 5 neden sırala."

input_ids = tokenizer(prompt, return_tensors="pt").input_ids

output = model.generate(
    input_ids=input_ids,
    pad_token_id=tokenizer.pad_token_id,
    max_length=100
)

output

tensor([[18486, 23877,  2106,  5677, 29186,   373,   743,   843,   915,  3624,
            14,   603, 50174,   277,  7993,   717,   199, 18486, 23877,  2106,
          5677, 29186,   373,   743,   843,   915,  3624,    14,   199, 18486,
          6310, 22447,    14,   517,  1010,  8297, 11112,   417,   373,  3064,
         32522,    31,   199, 18486,  6310, 22447,    14,   517,  1010,  8297,
         11112,   417,   373,  3064, 32522,    31,   199, 18486,  6310, 22447,
            14,   517,  1010,  8297, 11112,   417,   373,  3064, 32522,    31,
           199, 18486,  6310, 22447,    14,   517,  1010,  8297, 11112,   417,
           373,  3064, 32522,    31,   199, 18486,  6310, 22447,    14,   517,
          1010,  8297, 11112,   417,   373,  3064, 32522,    31,   199, 18486]])

In [ ]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [ ]:
#Yukarıda gösterilen token dizisi, "decode" fonksiyonu ile metin haline getiliir.

text = tokenizer.decode(output[0], skip_special_tokens=False)
print(text)

Zor günlere rağmen hayatı sevmek için 5 neden sırala. - KizlarSoruyor
Zor günlere rağmen hayatı sevmek için 5 neden sırala.
Zor günler geçirdik. Bu zor günleri atlatmak için neler yapmalıyız?
Zor günler geçirdik. Bu zor günleri atlatmak için neler yapmalıyız?
Zor günler geçirdik. Bu zor günleri atlatmak için neler yapmalıyız?
Zor günler geçirdik. Bu zor günleri atlatmak için neler yapmalıyız?
Zor günler geçirdik. Bu zor günleri atlatmak için neler yapmalıyız?
Zor


## Şimdi de fine-tuning sonrası aynı soruya tekrar cevap üretelim:

In [ ]:
!pip uninstall huggingace_hub
!pip install huggingface_hub

!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 22.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.8 MB/s eta 0:00:00


In [ ]:
import datasets
from datasets import load_dataset
from datasets import Dataset as Ds
from torch.utils.data import Dataset
from transformers import DataCollatorForLanguageModeling, Trainer, TrainingArguments

In [ ]:
ds_len = 2000       #You can experiment with less training to see the result.
                    #We'll just use a tiny bit of the dataset.

                    #Larger numbers give better results but last longer.

dataset = load_dataset("merve/turkish_instructions")["train"].select(range(ds_len))

Yukarıda "merve/turkish_instructions" veri setinin bir kısmını yükledik. İnceleyelim:

In [ ]:
dataset

Dataset({
    features: ['Unnamed: 0', 'talimat', ' giriş', ' çıktı'],
    num_rows: 2000
})

Yüklediğimiz veri setinde "talimat" alanında sorular, " çıktı" alanında ise cevaplar yer almaktadır.

GPT-2 modelinin eğitimi için soru ve cevapların birbirini takip ederek yer aldığı örneklerden oluşan yeni bir veri seti oluşturalım:

In [ ]:
train_dataset = { "example":  [talimat + çıktı for talimat, çıktı in zip(dataset["talimat"], dataset[" çıktı"])]}
train_dataset = Ds.from_dict(train_dataset)

new_dataset = datasets.DatasetDict( {"train":train_dataset} )
new_dataset = new_dataset["train"]

# GPT-2 girdilerini sürekli halde alır. Bu nedenle girdi-çıktı ikilisini bir araya getirerek yeni bir veri seti oluşturuyoruz.

In [ ]:
new_dataset

Dataset({
    features: ['example'],
    num_rows: 2000
})

In [ ]:
class MyDataSet(Dataset):
  def __init__(self, tokenizer, data, block_size):
    self.tokenizer = tokenizer
    self.data = data
    self.block_size = block_size

  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx):
    item = self.data[idx]
    tokenized_inputs = self.tokenizer(
        item["example"],
        truncation=True,
        padding="max_length",
        max_length=self.block_size,
        return_tensors="pt"
    )
    return tokenized_inputs

In [ ]:
data = MyDataSet(tokenizer, new_dataset, 512)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
print(dir(data))

['__add__', '__annotations__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_is_protocol', 'block_size', 'data', 'tokenizer']


In [ ]:
print(data.data)
print(data.tokenizer)

Dataset({
    features: ['example'],
    num_rows: 2000
})
GPT2TokenizerFast(name_or_path='ytu-ce-cosmos/turkish-gpt2', vocab_size=50257, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}


Aşağıda fine-tuning işlemi için gerekli olan parametreler ayarlanmaktadır:

In [ ]:
training_args = TrainingArguments(
    per_device_train_batch_size=8,
    num_train_epochs=10,
    learning_rate=5e-5,
    logging_steps=100,
    output_dir='./results'
)

trainer= Trainer(
    model=model,
    args=training_args,
    train_dataset=data,
    eval_dataset=None,
    data_collator=data_collator,
)

In [ ]:
# GPU kullanımınızı görüntülemek, iyileştirmek için bu komutları kullanabilirsiniz.

#torch.cuda.memory_allocated()

#torch.cuda.empty_cache()

#import os
#os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"


#!nvidia-smi    #nvidia gpu'larında anlık kullanımları görüntülemek için kullanılır.

In [ ]:
trainer.train()

TrainOutput(global_step=2500, training_loss=1.363742933654785, metrics={'train_runtime': 3149.6921, 'train_samples_per_second': 6.35, 'train_steps_per_second': 0.794, 'total_flos': 5225840640000000.0, 'train_loss': 1.363742933654785, 'epoch': 10.0})

In [ ]:
model.eval()

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [ ]:
prompt ="Zor günlere rağmen hayatı sevmek için 5 neden sırala."

input_ids = tokenizer(prompt, return_tensors ="pt").input_ids
attention_mask = tokenizer(prompt, return_tensors = "pt").attention_mask

input_ids = input_ids.to(device)
attention_mask = attention_mask.to(device)

input_ids

tensor([[18486, 23877,  2106,  5677, 29186,   373,   743,   843,   915,  3624,
            14]], device='cuda:0')

Eğitilen modelle aynı soru için yanıtlar üretelim:

In [ ]:
output = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    pad_token_id=tokenizer.pad_token_id,
    max_length=100,
    num_beams=5,
    temperature=1.5,
    top_k=50,
    do_sample=True
)

In [ ]:
output

tensor([[18486, 23877,  2106,  5677, 29186,   373,   743,   843,   915,  3624,
            14,    17,    14, 12010,   299, 28704,  4106,  7225,   386,    14,
         42399,   349,   299, 31710,  7605,  7225,   609,    14,  6440,  2265,
          2471,  7225,   750,    14, 41055,   299, 19616, 22873, 12548,  7225,
           743,    14, 42399,   349,   299, 31710,  7605,  7225,   950,    14,
          8718,   840,   299, 21602,  5321, 11419,  7225,  1023,    14, 18592,
          1435, 11419,  7225,  1121,    14, 42399,   349,   299, 31710,  7605,
          7225,  1248,    14,  2342, 18572,   299, 29534, 26812,  7225,  1016,
            14,  8171,   307, 12159,  6458, 12651,  7225,  1564,    14,  8171,
           307, 12159,  1093, 11904,  7225,  1443,    14, 42399,   349,   299]],
       device='cuda:0')

In [ ]:
text = tokenizer.decode(output[0], skip_special_tokens=True)
print(text)

Zor günlere rağmen hayatı sevmek için 5 neden sırala.1. Birlik ve Beraberliğin önemi 2. Dirençli ve dirençli olmanın önemi 3. Arkadaş edinmenin önemi 4. Farkındalık ve şükran pratiğinin önemi 5. Dirençli ve dirençli olmanın önemi 6. Paylaşmaya ve üretmeye teşvik etmenin önemi 7. Kendini ifade etmenin önemi 8. Dirençli ve dirençli olmanın önemi 9. Empati ve empati kullanmanın önemi 10. Zor bir mücadelede işbirliği yapmanın önemi 11. Zor bir mücadelede birlikte çalışmanın önemi 12. Dirençli ve


In [ ]:
trainer.save_model("SFT-cosmos-gpt2-merve-2k")

In [ ]:
tokenizer.save_pretrained("SFT-cosmos-gpt2-merve-2k")

('SFT-cosmos-gpt2-merve-2k/tokenizer_config.json',
 'SFT-cosmos-gpt2-merve-2k/special_tokens_map.json',
 'SFT-cosmos-gpt2-merve-2k/vocab.json',
 'SFT-cosmos-gpt2-merve-2k/merges.txt',
 'SFT-cosmos-gpt2-merve-2k/added_tokens.json',
 'SFT-cosmos-gpt2-merve-2k/tokenizer.json')